Update infra-ci--cd.yml

diff --git a/.github/workflows/infra-ci--cd.yml b/.github/workflows/infra-ci--cd.yml
--- a/.github/workflows/infra-ci--cd.yml
+++ b/.github/workflows/infra-ci--cd.yml
@@ -6,6 +6,27 @@ on:
       - main
 
 jobs:
+  install_tflint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download TFLint
+        run: |
+          curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.35.0/tflint-linux-amd64.zip
+          # Check the file size
+          ls -lh tflint-linux-amd64.zip
+
+      - name: Unzip TFLint
+        run: |
+          unzip tflint-linux-amd64.zip
+          # If unzip fails, print debug information
+          if [ $? -ne 0 ]; then
+            echo "Unzip failed, exiting..."
+            exit 1
+          fi
+
+      - name: Move TFLint to /usr/local/bin/
+        run: |
+          sudo mv tflint /usr/local/bin/
   terraform-deploy:
     runs-on: ubuntu-latest
 
